import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import { ReactQueryClientProvider } from "./components/ReactQueryClientProvider";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <head>
        <ColorSchemeScript />
      </head>
      <html lang="en" {...mantineHtmlProps}>
        <body>
          <MantineProvider>{children}</MantineProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
